### ISSUE TITLE
Question about TOI solver in dyn4j

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#112]
While working with box2d's continuous detection code it was easy to spot some differences with the one in dyn4j, so here I am curious about how the design came to be.

After finding the minimum TOI box2d builds an island with the bodies, uses the position solver for those bodies and then updates the affected contacts (more or less).
On the other hand dyn4j will just interpolate the bodies to the TOI so they're solved in the next frame with no extra corrections on the SolveTOI code (correct me if I'm wrong).

In some recent tests I found out box2d's approach to be unstable. While it works ok for few sparse bullet bodies it freaks out when multiple bullets collide.
Bodies and joints start glitching, producing very weird optical artifacts, effectively destroying the simulation. 
On the other hand dyn4j is pretty smooth, I have not seen strange behavior/movement of bodies with (the default) CCD.ALL which makes me think it's approach is simpler and superior.

Any comments on the implementation and differences, William? I would like to find out more details about this. Thanks

**Comment by wnbittle** [comment]
I can't really speak to what box2d is doing unfortunately.  I remember looking at the code but then quickly pivoting to my own implementation of the solution described in [Continuous Collision Detection and Physics](https://www.gamedevs.org/uploads/continuous-collision-detection-and-physics.pdf).  The implementation is in [ConservativeAdvancement.java](https://github.com/dyn4j/dyn4j/blob/master/src/main/java/org/dyn4j/collision/continuous/ConservativeAdvancement.java).  

dyn4j's implementation is far from perfect.  I opted to not track closest points between objects like Brian Mirtich.  Instead, it's implemented as a post detection/resolution step that has to check _every_ dynamic (ALL) or bullet (BULLETS_ONLY) body against _every_ other non-bullet body in the world.  I use the pre- and post-detection/resolution transforms and root find to see if there's a missed collision.  If I detect there's a collision, I interpolate the collision position for both bodies so they can be detected by static collision detection and resolved by the impulse solver in the next frame (as you mentioned).  The solveTOI() and solveTOI(Body) methods are what control what bodies are tested and there are a number of conditions being used to lower the number of detections that must be made. 

This results in the following behavior:
1. **Performance** - It's not a problem in worlds with a small number of bodies, but large worlds would struggle.  This is because we don't know what pairs we need to check so we end up having to check most of them.  On top of that, root finding is not a particularly performant task.  On the flip side, the process typically exits quickly when there's no missed collision, but doing _no_ work is always better than doing _a little bit_ of work.
2. **Time loss** - Because the bodies are advanced, then backtracked when a collision is found, the motion can appear to stutter when there's a lot of these collisions in sequence.  The reason it appears this way is because we move the bodies back to the collision and don't try to catch them up to the current world time.
3. **_Potential_ for missed collisions** - In dyn4j's implementation, once a body has participated in a TOI, it can no longer participate in others in that same step.  This _could_ have the effect of missed collisions when dealing with a lot of fast/small moving objects.  I haven't seen this in my testing, but my testing hasn't been very extensive of this scenario.

**Comment by mtsamis** [comment]
Alright thanks for all the helpful info and the links! I think this approach produces better result anyway so it’s good you made your own implementation. 

About performance by the way, I know that solveTOI scales very bad with body count but this can be fixed to a great extend. I actually propose we implement this for v4. One can use the broadphase to find candidate overlapping swept AABB pairs instead of a double loop. I have tried this in the past as an experimental implementation and the results were very good. The only thing missing is a clean way to handle this different use of the broadphase and the API (see #63)

I think box2d tries to solve your point 3 in a way (by solving the collision and then allowing the body to participate again in another TOI) but this eventually makes the result even worse, mostly when multiple bullets collide.

Thanks
