### ISSUE TITLE
Can `RobustGeometry` be omitted when porting?

### ISSUE THREAD

**Issue by gkjpettet** [dyn4j/dyn4j#129]
As mentioned previously, I'm porting dyn4j to Xojo. I'm having issues with the `RobustGeometry` class in that the tests for it are failing for me. I've implemented most of the other geometry classes and they pass their tests. I'm trying to nail down the issue as to whether it's a problem with my implementation of `RobustGeometry` or `AdaptiveDecimal`. The `AdaptiveDecimal` tests are passing.

My question is this: If I can't figure out the issue with the `RobustGeometry` class, can it be omitted? I see it was only a recent-ish addition to the library and so I'm wondering if it's methods can be substituted with the other class's methods (for instance, `getLocation`. Is the `RobustGeometry` class deeply integral to the rest of the library? Searching the repo it doesn't look like its methods are used extensively.

**Comment by wnbittle** [comment]
`RobustGeometry `is currently only used in convex hull generation.  This was added to resolve the issues with IEEE and the `getLocation` method where it would report the wrong location due to numeric/precision error.  It is not used elsewhere at this time.  It's possible that it would be extended to convex decomposition, but it will not be used in the core library due to performance.  If omitted, there are cases where the convex hull algorithms will fail by throwing exceptions or even loop forever.

**Comment by mtsamis** [comment]
Hey @gkjpettet  what's the issue with the RobustGeometry tests for you? I can probably help with solving them.

On a sidenote here's some material as to why RobustGeometry was introduced: #73 #75 #76 #81 #83

**Comment by gkjpettet** [comment]
After much debugging it looks like I had ported the class and the tests correctly. The bug was in my `Signum` method (I'm having to port a lot Java's system Math library as it has functions not available natively to Xojo). There was an issue where Xojo was reporting 0.0 != 0000000000.1 (i.e a tolerance problem). I've corrected that bug and now all the tests are passing. Phew!

Thanks for explaining its use though @wnbittle and thank you for the offer of help @mtsamis. I now just need to see if I've optimised my `Signum` method enough.
