### ISSUE TITLE
EarClipping algorithm hangs

### ISSUE THREAD

**Issue by ykrapiva** [dyn4j/dyn4j#24]
I've been playing with EarClipping decomposer and found out that for certain vertices the code falls into indefinite loop freezing the application.
Version affected: 3.2.3

Could you please make a fix ?

`
@Test(timeout = 5000)
public void indefiniteLoop() throws Exception {
        new EarClipping().decompose(
                new Vector2(48.0, 1.0),
                new Vector2(70.0, -28.0),
                new Vector2(51.0, -58.0),
                new Vector2(17.0, -49.0),
                new Vector2(78.69931639118523, -52.394108883581644)
        );
    }
`

**Comment by ykrapiva** [comment]
Same happens with SweepLine

`@Test(timeout = 5000)
    public void sweepLineIndefiniteLoop() throws Exception {
        new SweepLine().decompose(
                new Vector2(15.0, -14.0), 
                new Vector2(17.0, -49.0), 
                new Vector2(51.0, -58.0), 
                new Vector2(70.0, -28.0), 
                new Vector2(136.56366555776418, -49.38052989277156)
        );
    }`

**Comment by wnbittle** [comment]
This will happen with any of the decomposition algorithms since they only support [Simple Polygons](https://en.wikipedia.org/wiki/Simple_polygon) without holes.  This is why the two you mention here do not work.  See the [javadocs](http://docs.dyn4j.org/v3.2.3/org/dyn4j/geometry/decompose/package-summary.html) for more details.

A contribution/patch would be the fastest way to get this supported in the library.

**Comment by ykrapiva** [comment]
I understand but the code should throw the exception like Bayazit code does.
I'll try to find some time and grasp the code to propose the reasonable fix

**Comment by wnbittle** [comment]
No pull request submitted and documentation states the intended input.
