### ISSUE TITLE
Java 9

### ISSUE THREAD

**Issue by io7m** [dyn4j/dyn4j#29]
Hello.

Do you have any plans to publish Java 9 modules for the project? I suspect with the lack of dependencies, you'll have an easier time of it than most.

**Comment by wnbittle** [comment]
Yeah, it should be pretty easy to do this.  It's been a while since I reviewed the feature and just need to understand the impact on earlier version of Java (for deployment).  As a side note, there's already pull requests for OSGi and truely Maven-izing the project that I still want to incorporate as well.  This will likely coincide with me splitting the source in this repo into many (main, tests, sandbox, etc).

**Comment by io7m** [comment]
Do you need a hand with any of this? I'm available.

**Comment by wnbittle** [comment]
Yes, I would like some help here, if you have some time.

I've split the projects and I've converted dyn4j to a true Maven project and attempted, using your pull request changes (thank you, this made things much easier), to modify it to build the appropriate OSGi bundle.

Can you verify that it is being built correctly for both Maven and OSGi.  From what I can tell, it looks right, but it would be nice if someone else could verify.

**Comment by io7m** [comment]
This all looks good to me, the build succeeds and gives the right results. Nice work!

I have a slight improvement I can make in a PR that makes deploying to Maven Central even easier (turns it into one command instead of three).

I'll also add a PR that updates the plugins to the latest versions. Quite a few core plugins had new releases when Java 9 came out. There's a slight adjustment you can make to the POM that can allow the [versions-maven-plugin](http://www.mojohaus.org/versions-maven-plugin/) to update plugin versions for you when you execute `mvn versions:update-properties`.

**Comment by io7m** [comment]
OK, so now I need to look into what it takes to produce a Java 9 module that works on releases as far back as Java 6. The basic issue is that you need to compile the module descriptor as Java 9 bytecode, but the rest of the files need to be Java 6 bytecode.

**Comment by io7m** [comment]
Ok, it seems that there are a few ways to do this. The most pleasant way involves requiring JDK 9 to *build* the project (but it'll only require >= JDK 6 to *run* the code). Are you OK with requiring JDK 9?

**Comment by wnbittle** [comment]
I'm trying that now - maybe you've had better luck?  

I updated the compilation values in the pom to:
```xml
<source>1.9</source>
<target>1.6</target>
```
And added the module-info.java file.  

It builds successfully (after adding a workaround for updating BND to 3.5.0), but I get "java.lang.UnsupportedClassVersionError" when I try to use the jar in a project that builds against anything less than 9.  I'm not sure what's going on there.  That should be working.

Eclipse doesn't even allow this scenario - which isn't that surprising. The target must be >= the compilation version.  If I'm not careful with the APIs that I choose, I could break compatibility without knowing.

What I'd like to do is generate a multi-release jar somehow, but from what I've read, this may not be available in the current maven tooling (I've seen some workarounds though).  What do you think about this option?  I wonder if it's even possible?  The only thing that would be in the /META-INF/versions/9 would be the module-info.class right now.  Sort of annoying.

Another not so nice option is to create a Java 9 branch and just perform merges from master over.  Deployments would be much more annoying.  Can you specify the Java version of a dependency in Maven so that you get the right one or would I need to name the Java 9 release something else - the effect being two dyn4j releases in Maven Central?

**Comment by io7m** [comment]
Have a look at that PR. I've done some informal testing and it appears to work on both Java 9 and Java 8 (I don't have an older JDK for testing, unfortunately). I think it alleviates your concerns about accidentally using APIs that won't work on Java 6 (via the "release" option). It doesn't involve multi-release jars, multiple branches, or any of those horrors. 😄 

The only downside is that IDEA 2017.2 detects the wrong JDK version, but that's a problem on their side, and just means you have to pick the right one explicitly. The newer IDEA might be able to cope with it. Not sure how Eclipse handles it.

**Comment by wnbittle** [comment]
Yeah, this looks good.  I've tested and the jar looks good and works with another project targeted for 1.6 (executing as 1.6 on a 1.8 JRE).  Very happy with this solution - thank you.

I'm going to leave this issue open until I test the gpg/deployment configuration as well.

**Comment by wnbittle** [comment]
Java 9 + OSGi version released.
