### ISSUE TITLE
Manifold Resolution - Multithreaded - Delayed Resolution

### ISSUE THREAD

**Issue by HelloMaybeIDontKnow** [dyn4j/dyn4j#35]
Hi,

I was planning to make a multithreaded project by trying to make a physics engine... well, multithreaded as much as possible for a research project.
Yes, I know many have tried and failed and that physics engines are not naturally very threading-friendly.

Maybe someone can answer me what would possibly happen if - due to threading - the collision resolving would happen delayed about X frames (fixed) after the initial collision.
X is a number between 1 and 32 or something.

AFAIK the resolver normally applies an impulse on the objects to possibly uncollide them next frame. (Don't know what happens when the time step is not fixed.).
A delayed resolution would mean that the impulse gets applied X frames later, so the objects penetrate even further before the single impulses apply. Would that work or become possibly unstable?

**Comment by wnbittle** [comment]
I think a more accurate statement is that Physics Engines are generally not thread safe.  I think that distinction is an important one.  You can certainly use the physics engine on a separate thread, but the difficulty is in synchronization.

The physics engine stores the state of objects: position, velocity, acceleration, orientation, etc.  If we are talking about a GUI application where those objects are rendered, then the renderer also has the state of the objects.  If we assume that the Physics Engine is the source of truth for object state and that it's lagging behind by 30 frames, it just means the renderer renders the same scene 30 times before the scene would change.  Sounds ok on the surface.  If we consider the context of an interactive game, user input should always be reflected immediately.  As such, we can't say the source of truth for object state is the Physics Engine any more, but now it's a hybrid.  

This is where the synchronization comes into play and where things start to break down.  If the user performs actions quickly enough, i.e. before the physics engine can resolve them, the user could break physical rules or the user's input would be overwritten with the updated state from the physics engine at some later time.  I think this is why focus on multithreading has been mainly _within_ the physics engine, while it's use with the rest of the application remains single threaded.

That said, one thing to consider is that a networked physical simulation is very similar to a multithreaded one.  The network is slow and you must reconcile physical interaction from multiple sources and synchronize it back to them.  They typically take the approach of the server is the source of truth, running the simulation itself.  The clients run the simulation too, but are synchronized with what the server says.  This is why you might see jumping backwards or other strange effects sometimes when there's network lag or even client side lag.

Another reason why multithreading with the physics engine doesn't happen often is because there are just so many ways to mitigate the physics engine's performance.  Culling, streaming, partitioning, and so on have made it not as important.  That's not true for all cases naturally.  Scientific, CGI, and related fields often can't take these paths, but they aren't interactive, so multi threading is much easier.

For your particular case, it's hard to say.  Are the objects being rendered storing their state in the physics engine?  If so, you'd just see 1-32 frames of nothing happening.  If the state is stored separately you'd have the same effect unless you manually advanced the objects in the scene on the UI thread.  The effect of that would be that you might penetrate something or even pass through something completely and then suddenly jump back due to the physics engine catching up.

It's certainly not a trivial problem and whatever solution is decided, it will be highly dependent on the application being written.
