### ISSUE TITLE
How to update, if FPS varies

### ISSUE THREAD

**Issue by mudlee** [dyn4j/dyn4j#36]
The gameloop I use does not guarantee the same frequency when I call world.update.
As I understood, this is normal (because swapping buffers might run a little longer sometimes), and this is why we pass an elapsed time to the update method. My problem is however, when my elapsed time has spikes in it, then when I query the position changes and apply on my world items, then the scene became laggy for the frame when the spike appears.

Example of my elapsed times:

    0.016895125
    0.01651961
    0.016706764
    0.016958213
    0.116231636 <- SPIKE
    0.016778305
    0.016688048
    0.01665092

You can see, there is one frame, where the elapsed time is `0.116231636`. In that frame, my let's say player sprite jumps a little bit more, than in the other frames. Why?

Every frame I run thiscode:
  
    long time = System.nanoTime();
    long diff = time - this.lastUpdateTime;
    lastUpdateTime = time;
    double elapsedTime = (double) diff / 1.0e9;
    System.out.println(elapsedTime);
    boolean updated=this.world.update(elapsedTime);

After this, if the world was `updated,` I iterate through the world items, and I use the `body.getChangeInPosition` method to retrieve the changes, and apply to my item's positions.

The interesting thing is that if I print the changes for the Y axis, when the spike appears I see no problem in the changes, see below 5 frames I debugged out. The spike appears in the 3rd frame.

    ELAPSED: 0.017004399
    CHANGE Y: -0.10072222222222216

    ELAPSED: 0.015985317
    CHANGE Y: -0.10344444444444445

    ELAPSED: 0.115819294 <- SPIKE
    CHANGE Y: -0.10616666666666674

    ELAPSED: 0.017143254
    CHANGE Y: -0.10888888888888859

    ELAPSED: 0.016584209
    CHANGE Y: -0.11161111111111088

**Comment by wnbittle** [comment]
Correct, usually that spike is a GC and normal.  You are calling the correct method as well.  The World.update(double) method will only execute a single step regardless of the elapsed time given.  The World has an internal clock to manage when it updates.

When you say 
> if I print the changes for the Y axis

Do you mean the y value of Body.getChangeInPosition()?

Did you by chance change the ContinuousDetectionMode in the settings to NONE?  Looking at the code for Body.getChangeInPosition() it relies on an internal transform that is captured at the beginning of the update, but that internal transform isn't set when ContinuousDetectionMode is NONE.

Out of curiosity, why are you updating the position rather than overwriting it directly from Body.getWorldCenter()?

**Comment by mudlee** [comment]
I'm new to dyn4j, previously I used libgdx's box2d wrapper. I'll check all of those you mentioned and will report back here

**Comment by wnbittle** [comment]
No problem - let me know what you find.

**Comment by mudlee** [comment]
It turned out it only exists on windows. On OSX and Linux it works perfectly, so I'm closing this.

**Comment by wnbittle** [comment]
Interesting.  Was it something with dyn4j on Windows or something else?

**Comment by mudlee** [comment]
I don't know. And it not "wasn't", it still a problem, but I experience with the same with libgdx's box2d, so that's why I suspect it's not dyn4j's fault
