### ISSUE TITLE
inconsistent world.update

### ISSUE THREAD

**Issue by fian46** [dyn4j/dyn4j#37]
hi im using dyn4j version 3.3.0

im facing issue when updating world. when calling update with delta 0.100 the simulation speed slowing down but when calling with update with 0.016 the simulation speed goes faster.

step to reproduce 
1 creating world
2 set gravity to none
3 add circle and set linear velocity to 10 

run world with different delta aka elapsed time and observe the different

**Comment by fian46** [comment]
if we increase the scale between delta let say first test 1 second and second test 0.1 second the result still wrong

**Comment by wnbittle** [comment]
I think the missing link here is that the World has its own internal clock.  In the first case, 0.1 is larger than the default update frequency of 1/60.  The update method in this case still only performs 1 iteration of the engine.  The effect is that extra time continues to accumulate, but is never evaluated.  There’s another version of the update method that allows you to specify the maximum number of iterations to perform per call.

**Comment by fian46** [comment]
can you give sample code for that update usage ? i think i am doing it wrong i am sorry. there no example in documentation-andvanced page please help me to pass the test

**Comment by wnbittle** [comment]
Have you read through the java docs for the world class, specifically the update methods?

I can post an example later.

**Comment by wnbittle** [comment]
The World class has an internal clock that determines when it performs a simulation step.  The internal clock is defaulted to 1/60.  This value is configurable via the world.getSettings().setStepFrequency(double) method.

Now, lets take your example of 0.01 and examine what it will do:

- Iteration 0: elapsed time = 0.01, 0.01 < 1/60 so no simulation is performed, hence (0,0) coordinates.
- Iteration 1: elapsed time = 0.02, 0.02 > 1/60 so a single simulation step is performed and the remaining time = 0.02 - 1/60 = 0.00333333333, coordinates = (0.16666666666666666, 0)
- Iteration 2: elapsed time = 0.01333333333, 0.01333333333 < 1/60 so no simulation is performed, coordinates = (0.16666666666666666, 0)
- Iteration 3: elapsed time = 0.02333333333, 0.02333333333 > 1/60 so a single simulation step is performed, coordinates = (0.3333333333333333, 0.0)
- And so on...

So as you can see, the internal clock of the World determines when it actually does simulation calculations.  If it hasn't been long enough, then nothing is done, the method immediately returns.

In the case of anything greater than 1/60, the World will perform **a single** simulation step, using up only 1/60 of the given elapsed time, with the rest stored in the internal time accumulator.  If the elapsed time is consistently above 1/60, the simulation will never catch up - the slowness you are seeing.

Hopefully the problem is clearer now.  The solution will depend on your use-case, but my guess is that you are looking for the update(double, int) method.  The second parameter in the update method allows you to tell the engine the maximum number of steps to perform per call.  By default its 1.

So changing the code to world.update(0.10, 10) should fix your problem:

- Iteration 0: elapsed time = 0.1, 0.1 > 1/60, so we need to perform 6 steps to catch up, left over time = 0
- Iteration 1: elapsed time = 0.1, 0.1 > 1/60, so we need to perform 6 steps to catch up, left over time = 0
- And so on...

On each iteration we are actually performing 6 simulation steps each using 1/60 elapsed time for a total of 0.1 elapsed time.

The [Javadoc](http://docs.dyn4j.org/v3.3.0/org.dyn4j-summary.html) has tons of information on these methods.

**Comment by fian46** [comment]
briliant it solve the problem 👍👍👍👍👍. i going to close this issue. what a noob me. thanks for the assistance. i saw the forum is going to retire so i ask this question here is it ok ?

**Comment by wnbittle** [comment]
Yeah, feel free to ask any questions here.
