### ISSUE TITLE
Max translation and max rotation

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#41]
While reading through the Island class, in lines 205 onwards:
```
// compute the translation and rotation for this time step
Vector2 translation = body.velocity.product(dt);
double rotation = body.angularVelocity * dt;

// make sure the translation is not over the maximum
if (translation.getMagnitudeSquared() > maxTranslationSqrd) {
	double ratio = maxTranslation / translation.getMagnitude();
	body.velocity.multiply(ratio);
}

// make sure the rotation is not over the maximum
if (rotation * rotation > maxRotationSqrd) {
	double ratio = maxRotation / Math.abs(rotation);
	body.angularVelocity *= ratio;
}
```

I can't understand why we multiply translation and rotation by `dt` when comparing to the settings maximum. As I imagine it one would want to limit the maximum velocity and rotation a body can obtain regardless of the current step time.
What is the logical interpretation of limiting those based on the current step time?

**Comment by mtsamis** [comment]
Well, I understand what this code does. I just don’t understand why would one want to do this.
If I have a moving car I imagine someone could say “this car should be moving with at most x speed”, but why would one want “this car should not move more than x meters in *some* time”? Depending how much time that is (correct me if I’m wrong but as I understand ‘dt’ is dynamic and will be changing during the simulation according to the elapsed time or user parameters) we can get various results.

**Comment by wnbittle** [comment]
We do it this way because velocity isn’t the issue.  What we are really trying to limit is the amount of motion in a time step.

The time step is set by the user and unless the user overrides it, it will be constant for every step (the world has an internal clock).

We could limit the velocity, but if we limit the translation we get an added benefit: the maximum translation is now independent of the time step the user wants.

If a user sets a maximum translation of 2, the max velocity would be 2/dt.  Based on this, you can see that the maximum velocity is based on the time step used - not a user defined constant.  If they decrease the time step, they’ve actually increased the maximum velocity allowed.

These settings are primarily for tunneling and managing the cost of CCD.

**Comment by mtsamis** [comment]
Alright, it makes more sense now! Thanks for clarifying
