### ISSUE TITLE
Basic wall obstacles failing

### ISSUE THREAD

**Issue by afonsomatos** [dyn4j/dyn4j#43]
I'm trying to implement a simple world:

- No gravity
- Have multiple square blocks (that are static, wall-like)
- Have a player (square block) controlled by arrows

I'm using `setLinearVelocity` to control the player's movement. The problem is, when I get closer to the square blocks, sometimes it seems my player body gets stuck while touching the square block.

Also, when the player is moving, it slides over the block. I want it to stop completely. Here's a gif of what's happening:

Only moving to the right, (10, 0) of linear velocity.
![sex0124](https://user-images.githubusercontent.com/10373500/50319592-17245600-04c0-11e9-8e2a-a84613b7a4df.gif)

**Comment by wnbittle** [comment]
A couple of things to look into:
1) make sure you are rendering the shapes properly, my guess is that the green shape is sliding because it rotated.
2) One recommendation I would have is to use the MotorJoint to control the player.
3) Take a look at the samples project for some examples of player control.
