### ISSUE TITLE
Change minimum version to Java 8 (currently it's Java 6)

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#51]
I was wondering how viable would it be to increase dyn4j's source level to Java 8.
Java 8 brings some cool features to use and it has very good adoption as of today (and with the new licensing around Java, devs will have to start using only the latest release).

Do you believe there can be some point where dyn4j can drop support for Java 6?
Although not the most necessary change, it would be great to have all of the new features (I was actually doing some neat changes with default interfaces).

**Comment by wnbittle** [comment]
Funny you bring this up.  After merging in the new broadphase pull request I had to fix a few <> syntax issues and had to replace List.sort (since 8) with Collections.sort.  The <> syntax isn't a big deal.  The sort replacement _could_ be a big deal if they are different implementations.  I haven't looked into though.  In addition, a new method was added to the BroadphaseDetector class, technically breaking any implementations outside of dyn4j since we don't have access to default methods in 6.

I would even say 8 is too old now.  Being able to support modules without the backward compatibility with 6 would simplify the build for sure and some of the new features would be really helpful.

Are you aware of any metrics that detail adoption by version by platform for example?

**Comment by mtsamis** [comment]
Sorry for the syntax leftovers, I actually didn't notice because I'm compiling with Java 11 ;)
I'll be more careful with that in the future. I think Collections.sort and List.sort are implemented in the same way. It's not like I used List.sort for some reason, I just forgot it was absent from Java 6.

I would say that Java 8 is too old as well, but I think a lot of people will continue using it for now. The only -somewhat recent- metric I found was [baeldung-java-in-2018](https://www.baeldung.com/java-in-2018.) As of today Java 6 & 7 should have very few users; I think those are mostly in the realm of legacy applications and don't affect dyn4j's userbase.

**Comment by mtsamis** [comment]
As a plus, now that https://github.com/dyn4j/dyn4j/pull/54 is under review, default interfaces would be really helpful there. Each class that supports rotations needs to have 6 or 12 different implementations (depending if inverse rotations exist) while with default interfaces that can be done with 2 for all classes.

**Comment by TMIndust** [comment]
I have a request: The project I am working on, getting closer to its final release every day, relies on dyn4j, currently. Android (and unnamed ARM consoles) only support Java 8 source.
It would be nice if the current crucial bugfixes could be released as a stable build on Maven first, before migrating to Java 14 or whatever.

At the moment I use a branch of the latest source but other developers (including me) might seek for a stable working Java <=8 version at a later stage.

**Comment by wnbittle** [comment]
@TMIndust Understood.  At this time there's no plans to changes the minimum version.  The next version and probably the one after that will still support Java 6.
