### ISSUE TITLE
Strange behaviour if a block moves over a serie of blocks all with the same size

### ISSUE THREAD

**Issue by ia97lies** [dyn4j/dyn4j#56]
I do some game prototype and for the physics I use dyn4j as it looks quite simple. I have now a very strange issue I can not overcome easily:
I have placed a series of 1x1 blocks as a surface and move with a 1x1 block over those blocks. If I move the block over that surface it feels like it would slide over a randomly rough terrain. It even happens that the moving block stuck completely and no force can move it in either direction, not even upward from that ground. As I attached the camera directly to that block without smoothing there is a small very fast jitter visible when it stuck.

I'm not sure if that is wellknown issue. If I use circle without inerta it is a bit better, in that case it does not stuck, but it still looks like a randomly rough terrain.

**Comment by mtsamis** [comment]
Would it be easy for you to provide a minimal reproducible example of this problem?
Otherwise at least some parts of how you produce this would be helpful (world creation, block movement etc).

On a side note have you tried turning off continuous collision detection? If not, then you can give it a shot (it's enabled by default); I have recently experienced some odd behavior with it.

**Comment by ia97lies** [comment]
It is a bit complicated for me to make a simple example as I use jMonkeyEngine and Zay-ES and it is a bit too much context for you. But in case you have something wher you can place 1x1 blocks with infinite mass (static) and one 1x1 block with normal mass you should be fine (I also have 5 times the earth gravity => (0, -50)).
place that as follow where 'o' is a static block and 'p' is the player block like this:


                                                   p
ooooooooooooooooooooooooooooooooooooooooo

Then move the player with force (or also with linear velocity, doesn't really matter). You will then see that the player behaves as if there is rough terrain and occasionally stuck completely without being able to go in any direction not even in the "air".

My workaround is to add logic to make one big physic block, which is quite tricky if I want to remove blocks during the game. I managed that as well, maybe not the worst idea as dyn4j does have less work/calculation but on the other side the static blocks ('o') should not lead to much calculation in the dyn4j engine right?

And what do I lose if I turn off continuous collision detection? Why is that default? What is the alternative?

**Comment by mtsamis** [comment]
I currently cannot reproduce this scene to check if and how this happens, but if you do sometime let me have a look at it.

Apart from that, maybe the extreme gravity is causing some problems? If you just want things to fall faster have you considered to make your blocks smaller and increase the scaling (to achieve the same scene but with smaller bodies)? I'm saying this because very high gravity could produce more problems for your simulation in the future.

Your workaround, having the ground as a continuous block, sounds a reasonable alternative to me (although it adds some complexity). It is well known that making smooth sliding in non-continuous terrains with physics engines is tricky to get right.

I suggested to turn off CCD just to see if it makes things better. CCD prevents [Tuneling](https://google.github.io/liquidfun/Programmers-Guide/html/image_0.png) when an object moves fast enough to get through another in a single time step (which is not your case here). But CCD has a huge computational cost so it is better to selectively enable it. The default is CCD for all objects but you can change it to act only on 'bullet' objects (ie only on bodies that have `setBullet(true)`) or even disable it if you think it won't cause problems.

You can tweak CCD and many other parameters that may prove useful by changing your world's [Settings](https://github.com/dyn4j/dyn4j/blob/master/src/main/java/org/dyn4j/dynamics/Settings.java).

**Comment by ia97lies** [comment]
Thanks for all the suggestions. I will try them, specially the CCD! I only will need CCD for the fast flying stuff like the fragments I use for my explosions (which looks really really nice thanks to dyn4j) and probably have more CPU power left which is always desirable in a game :)

"It is well known that making smooth sliding in non-continuous terrains with physics engines is tricky to get right."
=> so actually it is well-known then, I guess the collision detection of the two edges and the transition from one block to another combined with floating point inaccuracy may cause my issue. Btw. I think I had the same effect for normal gravity (0, -10), but I have to re-check that.

**Comment by mtsamis** [comment]
Yeah, definitely enable CCD only for fast objects. The save in CPU time is enormous.

By well known I mean that it is a re-emerging problem and there have been various solutions suggested with other 2d physics engines as well (you can check for similar issues with box2d's users; I think box2d has some specific mechanisms just for this case).

One last note: you could try a compound shape that better fits your needs. Think of a Rectangle with 4 smaller Circles attached to it's corners (ie a body consisting from 5 shapes). This will probably provide better sliding and more smooth transitions.

**Comment by ia97lies** [comment]
I like you last note actually, I think this can solve nearly all my problems :) I'll try that.

One last question: If do all with 1x1 static cubes and as you said the movable parts I make with a cube and 4 wheels  on each corner, is that much more expensive CPU wise? I mean compared to grouped static cubes?

Ok doesn't matter too much as I probably have an algorithm for grouping, but if i could do without I could go rid of a lot of ugly complicated code and I like to go rid of code, especially complicated code :)

**Comment by ia97lies** [comment]
Turn off CCD solves the problem, unfortunately my character falls through floors if I do a dive. So next try will be with those wheels.

**Comment by mtsamis** [comment]
Good to know!
About the cpu part; it really depends on your needs. How many bodies will there be on your simulation. How many will be bullet bodies? How many will be active? How many collision are expected to happen each frame?
Of course those are a lot of factors, but it all depends. You should probably profile and stress test your simulations to see if performance is ok. Only if it’s not you should start optimizing further. 
But what you describe does not sound overkill, I think it should be ok both ways (even without grouping). 

Also (especially if you run into performance problems) keep in mind that the current HEAD in this repo has a lot meaningful optimizations compared to the latest release official (3.3.0). 

In a crude estimate I think you can relatively  easily get stable 60 fps at 1000 bodies

**Comment by mtsamis** [comment]
Interesting to hear that disabling CCD solves those problems. I’m really starting to suspect there are some loose ends with the CCD algorithms, since I had some problems recently as well.

I’ll be making some testing and search for possible bugs specifically for CCD, but this will probably take some time. You can keep an eye here to check for updates on this.

**Comment by ia97lies** [comment]
Hey thanks a lot for your support, appreciate that.

I solved it now relatively simple, in the update loop I look how fast my player is and after a threshold I simply I do body.setBullet(true). If it is just on the ground it will never reach that threshold. So actually problem solved for me so far and I think even CPU wise this is a good solution. Smooth sliding on the wall, no strange behaviour.

And true I will simply do a stress test to see where the limit is. I would luckily go rid of my block system I introduced as it is hard to maintain/fix/understand so far, specially when I want to break certain blocks.

**Comment by ia97lies** [comment]
you can close the issue, I guess I have no further questions, except you want to keep it open for what ever reason.

**Comment by mtsamis** [comment]
You’re welcome! btw this is not my physics engine ;)
dyn4j’s creator and main maintainer is William Bittle (wnbittle as shown here on github). I just have been working a lot with dyn4j lately and thought I could help you out! 
Cheers

**Comment by maheshkurmi** [comment]
I know I m late for the party, but this should help you a lot.

http://forum.dyn4j.org/viewtopic.php?f=3&t=262
