### ISSUE TITLE
Polygon.contains( ... ) unprecise!

### ISSUE THREAD

**Issue by mrdlink** [dyn4j/dyn4j#61]
Hello,
I tried to write myself an algorithm to map squares to any given polygon shape. I therefore use the contains() method of the Polygon class a lot, checking which corners of the square are inside the polygon shape.
With some shapes this works perfect. But with some shapes the method sometimes returns true for points that are clearly outside of the polygon shape. For example:

`Polygon(
				Vector2(2.0, 0.0),
				Vector2(4.0, 0.0),
				Vector2(7.0, 3.0),
				Vector2(7.0, 5.0),
				Vector2(5.0, 7.0),
				Vector2(3.0, 7.0),
				Vector2(0.0, 4.0),
				Vector2(0.0, 2.0)
		)`

When I call `contains(Vector2(0.0, 0.0))` on this polygon object it returns true. Though the point (0, 0) is definetly not inside the polygon shape.

What do you think? Is this a precision issue of the conatins() method or some other issue?

**Comment by mtsamis** [comment]
Hey,
I just checked the source of Polygon#contains method; it turns out this is a bug not some sort of precision problem. When the point being checked is co-linear with the first side(s) of the polygon this method will return always true (you can see that in your case (0, 0) (2, 0) and (4, 0) are co-linear as well). 

@wnbittle I'll go ahead and do some research on what would be a good way to fix this;
We should also check other similar cases where co-linear points can give wrong output & add unit tests for those cases.

**Comment by wnbittle** [comment]
Thanks for the report and reproduction case.  I've fixed the issue in the Polygon class.  @mtsamis if you are willing to look at any other places where this could be a problem that works for me.

**Comment by mtsamis** [comment]
@wnbittle  I think commit 729e8df is unnecessarily complex solution for this. Normally co-linearity should not be a problem because for a polygon at least one side won't be co-linear with the point being tested. I think the problem is that the variable `last` is not updated in the loop.
I wasn't be able to run this but wouldn't it be enough to add a single line:

```
...
if (last * location < 0) {
    return false;
}

last = location; // update last location
...
```

**Comment by wnbittle** [comment]
My intent was to exit early in those cases but I forgot that I allow coincident edges on polygons so that won't work.  I've updated the code based on your recommendation with a slight tweak - we need to always ignore a location of 0.  Otherwise we may not catch the changing of the sign and report the wrong value.  The other thing to consider is that this wouldn't work for a degenerate polygon (zero area) and the point is coincident with all the edges.

**Comment by mtsamis** [comment]
Great, I think this one is solved now! I also made a check for other uses of Segment.getLocation and didn’t see any other possible bugs when the result is 0.
